---
# Global logrotate configuration

- name: Deploy global logrotate configuration
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: Validate logrotate configuration
