---
# Custom logrotate configuration management

- name: Deploy custom logrotate configurations
  template:
    src: custom-config.j2
    dest: "/etc/logrotate.d/managed-{{ item.name }}.conf"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ logrotate_custom_configs }}"
  loop_control:
    label: "{{ item.name }}"
  notify: Validate logrotate configuration

- name: Find all managed logrotate configs
  find:
    paths: /etc/logrotate.d
    patterns: 'managed-*.conf'
  register: managed_configs

- name: Remove obsolete managed configs
  file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ managed_configs.files }}"
  loop_control:
    label: "{{ item.path | basename }}"
  when:
    - managed_configs.files is defined
    - item.path | basename | regex_replace('^managed-(.+)\\.conf$', '\\1') not in (logrotate_custom_configs | map(attribute='name') | list)
