---
# Documentation generation for logrotate configuration

- name: Ensure documentation directory exists
  file:
    path: "{{ doc_output_dir }}/{{ inventory_hostname }}"
    state: directory
    mode: '0755'
  delegate_to: localhost
  become: false
  run_once: false
  changed_when: false

- name: Generate markdown documentation
  template:
    src: docs/logrotate.md.j2
    dest: "{{ doc_output_dir }}/{{ inventory_hostname }}/logrotate.md"
    mode: '0644'
  delegate_to: localhost
  become: false
  changed_when: false

- name: Generate JSON documentation
  template:
    src: docs/logrotate.json.j2
    dest: "{{ doc_output_dir }}/{{ inventory_hostname }}/logrotate.json"
    mode: '0644'
  delegate_to: localhost
  become: false
  when: doc_format in ['both', 'json']
  changed_when: false
